name:hola-mundo
on:[push]
jobs:
    Ejecutar-programa: hola-mundo
    runs-on: Ubuntu-latest
    steps:
    - name: Verificar repositorio
      uses: actions/checkout@v3
    - name: 
      run: echo "USERNAME=${{ github.actor}}# >> $GITHUB_ENV
    - name:Coorrer script 
      run: python main.py  #ajustar nombre
